theme: jekyll-theme-cayman
title: シフト管理システム
description: 実績入力の効率化
show_downloads: false
github:
  is_project_page: false
markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
